export * from './contract'
export { educationAndEtc } from './education'
export { history } from './history'
export { introduces } from './introduce'
export { projects } from './project'
export { skills } from './skill'
